### ISSUE TITLE
Links to github/docs are failing

### ISSUE THREAD

**Issue by Sebring** [marko-js/marko-js.github.io#2]
I guess these are generated files or I'd edit and PR. However links in the original MD are 
`https://github.com/marko-js/cli/blob/master/packages/migrate/README.md`
but resolves to
`https://github/docs/.com/marko-js/cli/blob/master/packages/migrate/README/`
here causing them to fail on the official site.

Example: [https://markojs.com/docs/marko-5-upgrade/#step-2-deal-with-deprecations](https://markojs.com/docs/marko-5-upgrade/#step-2-deal-with-deprecations) - link `marko migrate`

**Comment by DylanPiercey** [comment]
Should be fixed now, appreciate the heads up!
